# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-11 00:29
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='extra',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bot',
            name='username',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='command',
            name='response',
            field=models.CharField(max_length=1024),
        ),
    ]
